 version: 2
 jobs:
   build:
     working_directory: ~/crow
     docker:
       - image: geppettoapps/crystal-libxml2-node:0.22.0
     steps:
       - checkout
       - run: |
           crystal deps
           crystal tool format --check src spec
           crystal spec
